<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sentry_client_js"
 *
 * Auto generated by Extension Builder 2016-11-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Client-side error reporting with Sentry',
    'description' => 'Client-side error reporting with Sentry (Raven.js)',
    'category' => 'plugin',
    'author' => 'AOE GmbH',
    'author_email' => 'dev@aoe.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.4.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-7.6.99',
        ),
        'conflicts' => array(),
        'suggests' => array(),
    ),
);
